# Generated by Django 4.1.5 on 2023-01-03 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('udi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='watermark_images')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
    ]
